#!/bin/bash

# nixos vs merlin
if [ -e /usr/local/share/OpenMPI ]; then
    PREFIX="--prefix /usr/local/share/OpenMPI"
fi

N=${1:-10};
mpic++ ${PREFIX:-} -o ots ots.cpp

dd if=/dev/random bs=1 count="$N" of=numbers 2>/dev/null
mpirun ${PREFIX:-} --oversubscribe -np "$N" ots
rm -f ots numbers
